const employees = [
  {
    id: 1,
    firstname: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Prepare Sales Report",
        description: "Compile and summarize weekly sales data.",
        date: "2025-11-25",
        category: "Reporting",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Client Follow-Up",
        description: "Call 5 pending clients regarding proposals.",
        date: "2025-11-26",
        category: "Communication",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update Product Listings",
        description: "Add new product details to the inventory system.",
        date: "2025-11-24",
        category: "Inventory",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Attend Team Meeting",
        description: "Discuss upcoming sprint goals.",
        date: "2025-11-27",
        category: "Meetings",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Review User Feedback",
        description: "Analyze customer feedback and list improvements.",
        date: "2025-11-26",
        category: "Analysis",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 2,
    firstname: "Vivaan",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        title: "Fix UI Bugs",
        description: "Resolve navbar responsiveness issues.",
        date: "2025-11-25",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Push Code Updates",
        description: "Deploy latest build to staging server.",
        date: "2025-11-26",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Database Backup",
        description: "Run weekly full backup.",
        date: "2025-11-24",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Server Monitoring",
        description: "Check CPU and memory usage logs.",
        date: "2025-11-27",
        category: "IT",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Team Code Review",
        description: "Review pull requests of junior devs.",
        date: "2025-11-26",
        category: "Development",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 3,
    firstname: "Priya",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Content Writing",
        description: "Write SEO-optimized content for homepage.",
        date: "2025-11-23",
        category: "Content",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Keyword Research",
        description: "Analyze competitor websites and gather keywords.",
        date: "2025-11-24",
        category: "SEO",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Social Media Scheduling",
        description: "Plan posts for the next 7 days.",
        date: "2025-11-25",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Blog Revision",
        description: "Update outdated blog articles.",
        date: "2025-11-27",
        category: "Content",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Create Ad Copy",
        description: "Draft ad copy for Google Ads campaigns.",
        date: "2025-11-26",
        category: "Marketing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 4,
    firstname: "Ishaan",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        title: "Inventory Check",
        description: "Verify stock levels for all products.",
        date: "2025-11-25",
        category: "Inventory",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Supplier Communication",
        description: "Email suppliers about delivery delays.",
        date: "2025-11-26",
        category: "Operations",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Warehouse Audit",
        description: "Inspect and document damaged items.",
        date: "2025-11-24",
        category: "Logistics",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Order Processing",
        description: "Handle 30+ customer orders.",
        date: "2025-11-27",
        category: "Operations",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update SKU Data",
        description: "Correct SKU mismatches in the system.",
        date: "2025-11-26",
        category: "Inventory",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },

  {
    id: 5,
    firstname: "Kavya",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        title: "Support Ticket Review",
        description: "Resolve pending customer issues.",
        date: "2025-11-25",
        category: "Support",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Respond to Emails",
        description: "Reply to important customer inquiries.",
        date: "2025-11-26",
        category: "Support",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Document Bugs",
        description: "Record bugs reported in the last 24 hours.",
        date: "2025-11-24",
        category: "QA",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Testing New Features",
        description: "Perform QA testing on latest app build.",
        date: "2025-11-27",
        category: "QA",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Prepare Support Summary",
        description: "Draft weekly support performance report.",
        date: "2025-11-26",
        category: "Support",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    firstname: "admin1",
    password: "123",
  },
];

export function setLocalStorage() {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
}

export default function getLocalStorage() {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return {
    employees: employees,
    admin: admin,
  };
}

// export default { getLocalStorage, setLocalStorage };
